<?php
define('SENDER_EMAIL_USER','<YOUR EMAIL>');
define('EMAIL_PASS','<YOUR PASSWORD>');
define('EMAIL_USERNAME','<YOUR USERNAME>');
define('EMAIL_USERNAME','<YOUR USERNAME>');
define('RECEIVER_USER','<YOUR NAME>');
?>
